import { writable } from 'svelte/store';

// Demo devices (8 total)
export const demoDevices = writable([
  {
    id: 'dev_001',
    name: 'Main Door Lock',
    type: 'lock',
    location: 'Madeira HQ — Ground Floor',
    status: 'locked',
    battery: 92,
    lastSeen: new Date(Date.now() - 2 * 60000),
    events: 12,
  },
  {
    id: 'dev_002',
    name: 'Office Door',
    type: 'lock',
    location: 'Madeira HQ — 2nd Floor',
    status: 'locked',
    battery: 87,
    lastSeen: new Date(Date.now() - 5 * 60000),
    events: 8,
  },
  {
    id: 'dev_003',
    name: 'Server Room Camera',
    type: 'camera',
    location: 'Madeira HQ — Basement',
    status: 'online',
    battery: null,
    lastSeen: new Date(Date.now() - 30000),
    events: 156,
  },
  {
    id: 'dev_004',
    name: 'Warehouse Door',
    type: 'lock',
    location: 'Warehouse A',
    status: 'unlocked',
    battery: 45,
    lastSeen: new Date(Date.now() - 10 * 60000),
    events: 94,
  },
  {
    id: 'dev_005',
    name: 'Back Gate Lock',
    type: 'lock',
    location: 'Warehouse A',
    status: 'locked',
    battery: 78,
    lastSeen: new Date(Date.now() - 15 * 60000),
    events: 23,
  },
  {
    id: 'dev_006',
    name: 'Parking Camera',
    type: 'camera',
    location: 'Warehouse A',
    status: 'online',
    battery: null,
    lastSeen: new Date(Date.now() - 1 * 60000),
    events: 234,
  },
  {
    id: 'dev_007',
    name: 'Conference Room Door',
    type: 'lock',
    location: 'Madeira HQ — 3rd Floor',
    status: 'locked',
    battery: 61,
    lastSeen: new Date(Date.now() - 25 * 60000),
    events: 5,
  },
  {
    id: 'dev_008',
    name: 'Reception Door',
    type: 'lock',
    location: 'Madeira HQ — Ground Floor',
    status: 'locked',
    battery: 88,
    lastSeen: new Date(Date.now() - 3 * 60000),
    events: 67,
  },
]);

// Demo access events
export const demoEvents = writable([
  {
    id: 'evt_001',
    deviceId: 'dev_001',
    deviceName: 'Main Door Lock',
    action: 'unlock',
    status: 'success',
    timestamp: new Date(Date.now() - 5 * 60000),
    user: 'Fernando Amorim',
    source: 'Mobile App',
  },
  {
    id: 'evt_002',
    deviceId: 'dev_002',
    deviceName: 'Office Door',
    action: 'lock',
    status: 'success',
    timestamp: new Date(Date.now() - 8 * 60000),
    user: 'Maria Silva',
    source: 'RFID Card',
  },
  {
    id: 'evt_003',
    deviceId: 'dev_001',
    deviceName: 'Main Door Lock',
    action: 'lock',
    status: 'success',
    timestamp: new Date(Date.now() - 12 * 60000),
    user: 'Fernando Amorim',
    source: 'Mobile App',
  },
  {
    id: 'evt_004',
    deviceId: 'dev_006',
    deviceName: 'Parking Camera',
    action: 'snapshot',
    status: 'success',
    timestamp: new Date(Date.now() - 15 * 60000),
    user: 'System',
    source: 'Motion Detected',
  },
  {
    id: 'evt_005',
    deviceId: 'dev_004',
    deviceName: 'Warehouse Door',
    action: 'unlock',
    status: 'success',
    timestamp: new Date(Date.now() - 20 * 60000),
    user: 'João Ferreira',
    source: 'PIN Code',
  },
  {
    id: 'evt_006',
    deviceId: 'dev_008',
    deviceName: 'Reception Door',
    action: 'unlock',
    status: 'success',
    timestamp: new Date(Date.now() - 25 * 60000),
    user: 'Recepção',
    source: 'RFID Card',
  },
  {
    id: 'evt_007',
    deviceId: 'dev_003',
    deviceName: 'Server Room Camera',
    action: 'snapshot',
    status: 'success',
    timestamp: new Date(Date.now() - 30 * 60000),
    user: 'System',
    source: 'Scheduled',
  },
  {
    id: 'evt_008',
    deviceId: 'dev_005',
    deviceName: 'Back Gate Lock',
    action: 'lock',
    status: 'success',
    timestamp: new Date(Date.now() - 35 * 60000),
    user: 'Segurança',
    source: 'Mobile App',
  },
  {
    id: 'evt_009',
    deviceId: 'dev_002',
    deviceName: 'Office Door',
    action: 'unlock',
    status: 'success',
    timestamp: new Date(Date.now() - 45 * 60000),
    user: 'Ana Costa',
    source: 'Bluetooth',
  },
  {
    id: 'evt_010',
    deviceId: 'dev_001',
    deviceName: 'Main Door Lock',
    action: 'unlock',
    status: 'success',
    timestamp: new Date(Date.now() - 60 * 60000),
    user: 'Fernando Amorim',
    source: 'Mobile App',
  },
]);

// Demo user
export const demoUser = writable({
  id: 'user_demo',
  name: 'Demo User',
  email: 'demo@jfaunify.pt',
  role: 'admin',
  org: 'JFA Demo Org',
  avatar: null,
});

// Demo stats
export const demoStats = writable({
  totalDevices: 8,
  activeDevices: 7,
  todayEvents: 42,
  uptime: 99.95,
});
